[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "lammps"
version = "2022.6.23.2.0"

[tool.scikit-build]
wheel.install-dir = "lammps"
cmake.args = [
    "-DLAMMPS_VERSION=stable_23Jun2022_update2",
]
