name: Build and upload to PyPI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # linux-64
          - os: ubuntu-latest
            python: 311
            platform_id: manylinux_x86_64
          # linux-aarch64
          - os: ubuntu-latest
            python: 311
            platform_id: manylinux_aarch64
          # linux-ppc64le
          - os: ubuntu-latest
            python: 311
            platform_id: manylinux_ppc64le
          # macos-x86-64
          - os: macos-13
            python: 311
            platform_id: macosx_x86_64
          # macos-arm64
          - os: macos-14
            bitness: 64
            python: 311
            platform_id: macosx_arm64
          # win64
          - os: windows-2019
            bitness: 64
            python: 311
            platform_id: win_amd64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-qemu-action@v3
        name: Setup QEMU
        if: matrix.platform_id == 'manylinux_aarch64' || matrix.platform_id == 'manylinux_ppc64le'
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.11'
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        if: matrix.os == 'windows-2019'
        with:
          mpi: msmpi

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: all
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
